-- MySQL Script generated by MySQL Workbench
-- mer 29 aoû 2018 10:00:17 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema COGIP-DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COGIP-DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COGIP-DB` DEFAULT CHARACTER SET utf8 ;
USE `COGIP-DB` ;

-- -----------------------------------------------------
-- Table `COGIP-DB`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP-DB`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COGIP-DB`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP-DB`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `street` VARCHAR(50) NULL,
  `number` VARCHAR(5) NULL,
  `zip` VARCHAR(10) NULL,
  `city` VARCHAR(30) NULL,
  `country` VARCHAR(30) NULL,
  `VAT` VARCHAR(12) NULL,
  `phone` VARCHAR(20) NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_type1_idx` (`type` ASC),
  CONSTRAINT `fk_company_type1`
    FOREIGN KEY (`type`)
    REFERENCES `COGIP-DB`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COGIP-DB`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP-DB`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(30) NULL,
  `lastname` VARCHAR(30) NULL,
  `phone` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `company` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_company1_idx` (`company` ASC),
  CONSTRAINT `fk_person_company1`
    FOREIGN KEY (`company`)
    REFERENCES `COGIP-DB`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COGIP-DB`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP-DB`.`bill` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `object` VARCHAR(30) NULL,
  `company` INT NOT NULL,
  `person` INT NOT NULL,
  PRIMARY KEY (`number`),
  INDEX `fk_bill_company1_idx` (`company` ASC),
  INDEX `fk_bill_person1_idx` (`person` ASC),
  CONSTRAINT `fk_bill_company1`
    FOREIGN KEY (`company`)
    REFERENCES `COGIP-DB`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_person1`
    FOREIGN KEY (`person`)
    REFERENCES `COGIP-DB`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
